### ISSUE TITLE
libEGL.so.1 should be bundled

### ISSUE THREAD

**Issue by probonopd** [helloSystem/LinuxRuntime#12]
Ultimaker-Cura-5.0.0-beta+1-linux.AppImage fails with

```
Traceback (most recent call last):
  File "cura_app.py", line 27, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "cura/CrashHandler.py", line 24, in <module>
    from PyQt6.QtWidgets import QDialog, QDialogButtonBox, QVBoxLayout, QLabel, QTextEdit, QGroupBox, QCheckBox, QPushButton
ImportError: libEGL.so.1: cannot open shared object file: No such file or directory
[3672] Failed to execute script 'cura_app' due to unhandled exception!
```

**Comment by probonopd** [comment]
libOpenGL.so.0 should also be bundled.

**Comment by probonopd** [comment]
Maybe we should just use a Live ISO instead as the runtime. Less work for us...

**Comment by probonopd** [comment]
libsndfile.so.1 should also be bundled.

**Comment by probonopd** [comment]
And the Nvidia stuff...

[linux-nvidia-libs-304-304.137.pkg](https://pkg.ghostbsd.org/stable/FreeBSD:13:amd64/latest/All/linux-nvidia-libs-304-304.137.pkg)
      [linux-nvidia-libs-340-340.108.pkg](https://pkg.ghostbsd.org/stable/FreeBSD:13:amd64/latest/All/linux-nvidia-libs-340-340.108.pkg)
      [linux-nvidia-libs-390-390.154.pkg](https://pkg.ghostbsd.org/stable/FreeBSD:13:amd64/latest/All/linux-nvidia-libs-390-390.154.pkg)
      [linux-nvidia-libs-470-470.161.03.pkg](https://pkg.ghostbsd.org/stable/FreeBSD:13:amd64/latest/All/linux-nvidia-libs-470-470.161.03.pkg)
